#!/bin/sh
# Set up environment for Veewee
# Usage: bootstrap
# Writtten by Mathias Lafeldt <mlafeldt@jimdo.com>

set -e

APP_ROOT="$(cd -P -- "$(dirname -- "$0")/../.." && pwd)"
cd "$APP_ROOT"

echo "Setting up your environment..."

if command -v ruby >/dev/null; then
    echo "  + Ruby found: $(ruby --version)"
else
    echo "  x You need to install Ruby."
    exit 1
fi

if command -v bundle >/dev/null; then
    echo "  + Bundler found: $(bundle --version)"
else
    echo "  x You need to install Bundler:"
    echo "    gem install bundler"
    exit 1
fi

if command -v VBoxManage >/dev/null; then
    echo "  + VirtualBox found: $(VBoxManage --version)"
else
    echo "  x You need to install VirtualBox."
    exit 1
fi

if command -v vagrant >/dev/null; then
    echo "  + Vagrant found: $(vagrant --version)"
else
    echo "  x You need to install Vagrant."
    exit 1
fi

echo "  + Bootstrapping your gems..."
bundle install --without="kvm windows" $BUNDLER_OPTS

echo "Done!"
