#!/bin/sh
# Build Vagrant base box using Veewee
# Usage: build-box <box definition>
# Writtten by Mathias Lafeldt <mlafeldt@jimdo.com>

set -e -x

BOX="${1:?box definition missing}"

APP_ROOT="$(cd -P -- "$(dirname -- "$0")/../.." && pwd)"
cd "$APP_ROOT"

# Global Veewee build options
export VEEWEE_PUPPET_VERSION="2.7.19"
export VEEWEE_CHEF_VERSION="10.24.0"

# Build Vagrant box with Veewee
bundle exec veewee vbox build --force "$BOX"
bundle exec veewee vbox export --force "$BOX"
